name: AccentedKeyboard
author: kunambi
category: Forms
tags: [touch, form, mobile, accent]
current: v1.0
copyright: "Thomas Kunambi, 23 Critters"
description: Accented Keyboard is a handy class for people using a different keyboard layout than the language they'd like to write with
